import React,{useEffect,useMemo,useState}from"react";
import{createRoot}from"react-dom/client";
import{LayoutDashboard,Map,Briefcase,MessageSquare,Activity,ChevronRight,Scale,Sparkles,Search,CheckCircle2,Clock3,ArrowUpRight,Menu,X,Target,BookOpen,ShieldCheck,Users,TrendingUp,ExternalLink,Filter,Send,UserRound,GraduationCap,Building2,CalendarDays,MapPin,Lightbulb,ChevronDown}from"lucide-react";
import"./styles.css";

const paths=[
{name:"Litigation & Advocacy",desc:"Court practice, advocacy, legal drafting and client representation.",roles:["Advocate","Legal Associate","Prosecutor","Legal Researcher"],skills:["Legal Research","Drafting","Advocacy","Case Analysis"],qual:"LLB + Bar enrollment"},
{name:"Judicial Service",desc:"Judicial examinations, court service and legal decision-making.",roles:["Civil Judge","Judicial Magistrate","Research Officer"],skills:["Law & Procedure","Judgment Writing","Reasoning","Current Affairs"],qual:"LLB + relevant competitive examination"},
{name:"Government Legal Service",desc:"Public-sector legal roles, policy, legislation and statutory work.",roles:["Legal Officer","Assistant Legal Adviser","Law Officer","Policy Officer"],skills:["Legislation","Legal Drafting","Public Law","Research"],qual:"LLB; role-specific requirements apply"},
{name:"Corporate / In-House Legal",desc:"Contracts, compliance, advisory work and commercial legal practice.",roles:["Legal Counsel","Compliance Officer","Contract Specialist","Legal Executive"],skills:["Contracts","Compliance","Negotiation","Commercial Law"],qual:"LLB; employer-specific requirements apply"},
{name:"Legal Research & Academia",desc:"Research, teaching, publications and policy analysis.",roles:["Research Assistant","Lecturer","Policy Researcher","Academic Fellow"],skills:["Research Methodology","Writing","Citation","Policy Analysis"],qual:"LLB/LLM depending on role"}];

const opps=[
{name:"Legal Research Intern",org:"Law & Policy Research",type:"Research",path:"Legal Research & Academia",location:"Pakistan",deadline:"Source verification pending",skills:["Research","Writing"],status:"Pending source"},
{name:"Junior Legal Officer",org:"Public Sector",type:"Government",path:"Government Legal Service",location:"Pakistan",deadline:"Source verification pending",skills:["Drafting","Public Law"],status:"Pending source"},
{name:"Research Assistant",org:"Academic / Policy Research",type:"Academia",path:"Legal Research & Academia",location:"Pakistan",deadline:"Source verification pending",skills:["Research","Analysis"],status:"Pending source"},
{name:"Legal Intern",org:"Corporate Legal Department",type:"Corporate",path:"Corporate / In-House Legal",location:"Pakistan",deadline:"Source verification pending",skills:["Contracts","Compliance"],status:"Pending source"}];

const API="/api";

async function api(path,options={}){const res=await fetch(API+path,{headers:{"Content-Type":"application/json",...(options.headers||{})},...options});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||"Request failed");return data}

const agents=[
["Research Agent","Collects candidate records from approved sources","Source discovery"],
["Verification Agent","Checks source, deadline, eligibility and freshness","Trust layer"],
["Career Intelligence Agent","Maps profiles to pathways and skill gaps","Career mapping"],
["Opportunity Matching Agent","Matches verified opportunities to student profiles","Personalisation"],
["Career Coach Agent","Creates grounded roadmaps and weekly actions","Action planning"]];

function App(){
 const[page,setPage]=useState("Dashboard"),[open,setOpen]=useState(false),[selectedPath,setSelectedPath]=useState(null),[selectedOpp,setSelectedOpp]=useState(null);
 const go=p=>{setPage(p);setOpen(false);window.scrollTo({top:0,behavior:"smooth"})};
 return <div className="app">
 <aside className={open?"side open":"side"}><div className="brand"><span className="mark"><Scale size={20}/></span><div><b>LegalPath</b><small>PAKISTAN</small></div></div>
 <div className="navLabel">WORKSPACE</div><nav>{[["Dashboard",LayoutDashboard],["Career Map",Map],["Opportunities",Briefcase],["AI Career Coach",MessageSquare],["Agent Activity",Activity]].map(([n,I])=><button key={n} className={page===n?"nav active":"nav"} onClick={()=>go(n)}><I size={18}/>{n}</button>)}</nav>
 <div className="sideCard"><Sparkles size={16}/><b>Career intelligence</b><span>Grounded in verified data when connected.</span></div>
 <div className="sideFoot"><span>LEGALPATH PAKISTAN</span><small>AI career operating system for law students</small></div></aside>
 <main><header><div className="headerLeft"><button className="hamb" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><div><span className="eyebrow">LEGAL CAREER INTELLIGENCE</span><h1>{page}</h1></div></div><button className="profile" onClick={()=>go("AI Career Coach")}><UserRound size={17}/></button></header>
 {page==="Dashboard"&&<Dashboard go={go}/>} {page==="Career Map"&&<CareerMap openPath={setSelectedPath}/>} {page==="Opportunities"&&<Opportunities openOpp={setSelectedOpp}/>} {page==="AI Career Coach"&&<Coach/>} {page==="Agent Activity"&&<Agents/>}
 </main>
 {selectedPath&&<PathModal path={selectedPath} close={()=>setSelectedPath(null)} go={go}/>}
 {selectedOpp&&<OppModal opp={selectedOpp} close={()=>setSelectedOpp(null)}/>}
 </div>
}

function Dashboard({go}){const[stats,setStats]=useState({pathways:paths.length,skills:"25+",agents:5,opps:0});useEffect(()=>{Promise.all([api("/career-pathways"),api("/skills"),api("/opportunities")]).then(([p,s,o])=>setStats({pathways:p.data?.length||paths.length,skills:(s.data?.length||0)+"",agents:5,opps:o.data?.length||0})).catch(()=>{});},[]);
 return <section className="content">
 <div className="hero"><div className="heroCopy"><span className="pill"><Sparkles size={14}/> AI-powered career intelligence</span><h2>Build your legal career<br/><em>with a clear path.</em></h2><p>LegalPath brings career pathways, skills, verified opportunities and AI-guided next steps into one workspace built for Pakistan's law students.</p><div className="actions"><button className="primary" onClick={()=>go("Career Map")}>Explore career paths <ArrowUpRight size={17}/></button><button className="secondary" onClick={()=>go("AI Career Coach")}>Build my roadmap</button></div></div><div className="heroVisual"><div className="orb"><Scale size={42}/></div><div className="orbStat"><b>05</b><span>career pathways</span></div><div className="orbit one"/><div className="orbit two"/></div></div>
 <div className="stats"><Stat icon={Map} value={String(stats.pathways).padStart(2,"0")} label="Career pathways"/><Stat icon={Target} value={stats.skills} label="Core skills"/><Stat icon={ShieldCheck} value={stats.opps} label="Opportunity records"/><Stat icon={Activity} value="05" label="AI agents"/></div>
 <div className="sectionHead"><div><span className="eyebrow">YOUR CAREER MAP</span><h3>Choose a direction</h3></div><button className="textBtn" onClick={()=>go("Career Map")}>View all <ChevronRight size={16}/></button></div>
 <div className="pathGrid">{paths.map((p,i)=><button className="pathCard" key={p.name} onClick={()=>go("Career Map")}><span>0{i+1}</span><h4>{p.name}</h4><p>{p.desc}</p><div className="cardArrow"><ChevronRight/></div></button>)}</div>
 <div className="lower"><div className="panel"><div className="panelTitle"><div><span className="eyebrow">OPPORTUNITIES</span><h3>Opportunity pipeline</h3></div><button className="textBtn" onClick={()=>go("Opportunities")}>Browse all</button></div>{opps.slice(0,3).map(o=><button className="opp" key={o.name} onClick={()=>go("Opportunities")}><div className="oppIcon"><Briefcase size={17}/></div><div><b>{o.name}</b><small>{o.org} · {o.location}</small></div><span className="tag">{o.type}</span></button>)}</div>
 <div className="panel coachMini"><span className="pill"><Sparkles size={13}/> Career Coach</span><h3>Know your next move?</h3><p>Start with your target career, interests and current skills. The coach can turn them into an actionable plan.</p><button className="primary" onClick={()=>go("AI Career Coach")}>Open coach <ArrowUpRight size={16}/></button></div></div>
 </section>
}
function Stat({icon:I,value,label}){return <div className="stat"><div className="statIcon"><I size={17}/></div><div><b>{value}</b><span>{label}</span></div></div>}

function CareerMap({openPath}){const[query,setQuery]=useState("");const filtered=paths.filter(p=>(p.name+p.desc).toLowerCase().includes(query.toLowerCase()));return <section className="content"><div className="pageIntro"><span className="eyebrow">CAREER PATHWAYS</span><h2>Five directions. One informed choice.</h2><p>Compare pathways by typical roles, core skills and qualification context. Final eligibility should always be checked against the relevant official source.</p></div><div className="mapTools"><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search pathways..."/></div><div className="toolNote"><BookOpen size={16}/> Explore a pathway to see its skill profile</div></div><div className="bigGrid">{filtered.map((p,i)=><article className="bigCard" key={p.name}><div className="cardTop"><span className="num">0{i+1}</span><span className="pathIcon"><Scale size={16}/></span></div><h3>{p.name}</h3><p>{p.desc}</p><div className="chips">{p.skills.slice(0,3).map(s=><span key={s}>{s}</span>)}</div><div className="line"/><div className="cardMeta"><span><Users size={14}/>{p.roles.length} role directions</span><span><GraduationCap size={14}/>{p.qual}</span></div><button className="outlineBtn" onClick={()=>openPath(p)}>Explore pathway <ChevronRight size={15}/></button></article>)}</div></section>}

function Opportunities({openOpp}){const[q,setQ]=useState(""),[type,setType]=useState("All"),[items,setItems]=useState(opps),[loading,setLoading]=useState(true);useEffect(()=>{api("/opportunities").then(r=>setItems((r.data||[]).map(o=>({name:o.title,org:o.organisation,type:o.type==="Employment"?"Government":o.type==="Research"?"Academia":o.type==="Internship"?"Research":"Corporate",path:o.pathway==="government"?"Government Legal Service":o.pathway==="corporate"?"Corporate / In-House Legal":"Legal Research & Academia",location:"Pakistan",deadline:o.deadline||"Not provided",skills:o.skills||[],status:o.verification_status==="verified"?"Verified":"Pending verification",source_url:o.source_url})))) .catch(()=>{}).finally(()=>setLoading(false));},[]);const filtered=useMemo(()=>items.filter(o=>(type==="All"||o.type===type)&&(o.name+" "+o.org+" "+o.path+" "+o.skills.join(" ")).toLowerCase().includes(q.toLowerCase())),[q,type]);return <section className="content"><div className="pageIntro"><span className="eyebrow">OPPORTUNITY INTELLIGENCE</span><h2>Find your next opportunity.</h2><p>Only records with traceable source information should become live recommendations. Seed records below remain clearly marked until verification is complete.</p></div><div className="oppToolbar"><div className="search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search roles, organisations or skills..."/></div><div className="filters">{["All","Research","Government","Academia","Corporate"].map(t=><button className={type===t?"filter active":"filter"} key={t} onClick={()=>setType(t)}><Filter size={13}/>{t}</button>)}</div></div><div className="table">{loading&&<div className="sourceBanner"><Clock3 size={18}/><div><b>Loading live backend records…</b><span>Fetching opportunity data from the LegalPath API.</span></div></div>}{filtered.map(o=><button className="opp row" key={o.name} onClick={()=>openOpp(o)}><div className="oppIcon"><Briefcase size={17}/></div><div className="grow"><b>{o.name}</b><small>{o.org} · {o.location}</small><div className="rowPath">{o.path}</div></div><span className="tag">{o.type}</span><span className="verified pending"><Clock3 size={14}/>{o.status}</span><ArrowUpRight size={17}/></button>)}</div><div className="sourceBanner"><ShieldCheck size={18}/><div><b>Source-first design</b><span>Every live opportunity will carry an original source URL, verification status and date checked. No vacancy is treated as verified just because an AI model generated it.</span></div></div></section>}

function Coach(){const[goal,setGoal]=useState(""),[submitted,setSubmitted]=useState(false),[interest,setInterest]=useState(""),[answer,setAnswer]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");const submit=async()=>{setBusy(true);setError("");setAnswer("");try{const r=await api("/agents/coach",{method:"POST",body:JSON.stringify({profile:{interests:interest,target:goal},question:goal||"Create a practical career roadmap.",context:{career_pathways:paths}})});setAnswer(r.answer||"No answer returned.");setSubmitted(true)}catch(e){setError(e.message)}finally{setBusy(false)}};const prompts=["I am a law student and want a government legal career.","Help me choose between advocacy and corporate law.","What skills should I build for legal research?"];return <section className="content"><div className="coachPage"><span className="pill"><Sparkles size={14}/> Grounded AI Career Coach</span><h2>Turn your profile into<br/><em>a practical roadmap.</em></h2><p>The coach will use verified pathway and opportunity data once the backend is connected. For now, this screen captures the profile inputs the production coach will use.</p><div className="coachGrid"><div className="coachForm"><label>What is your career goal?</label><textarea value={goal} onChange={e=>setGoal(e.target.value)} placeholder="e.g. I want to prepare for a government legal role..."/><label>What area interests you most?</label><select value={interest} onChange={e=>setInterest(e.target.value)}><option value="">Select an area</option>{paths.map(p=><option key={p.name}>{p.name}</option>)}</select><button className="primary full" disabled={busy} onClick={submit}><Send size={16}/> {busy?"Generating…":"Generate roadmap"}</button>{error&&<div className="saved"><Clock3 size={16}/> {error}</div>}{answer&&<div className="saved"><CheckCircle2 size={16}/><span>{answer}</span></div>}{submitted&&!answer&&!error&&<div className="saved"><CheckCircle2 size={16}/> Profile input saved locally for this session.</div>}</div><div className="coachAside"><div className="coachHeader"><div className="coachAvatar"><Sparkles size={17}/></div><div><b>LegalPath Coach</b><span>Grounded AI workflow</span></div></div><p>Try a starting question:</p>{prompts.map(x=><button key={x} onClick={()=>setGoal(x)}>{x}<ChevronRight size={15}/></button>)}<div className="coachRule"><ShieldCheck size={15}/><span>No invented vacancies, deadlines or legal requirements.</span></div></div></div></div></section>}

function Agents(){const[expanded,setExpanded]=useState(0),[activity,setActivity]=useState([]);useEffect(()=>{api("/agents/activity").then(r=>setActivity(r.data||[])).catch(()=>{});const id=setInterval(()=>api("/agents/activity").then(r=>setActivity(r.data||[])).catch(()=>{}),5000);return()=>clearInterval(id)},[]);return <section className="content"><div className="pageIntro"><span className="eyebrow">MULTI-AGENT SYSTEM</span><h2>AI workflow, with provenance.</h2><p>Each agent has a defined responsibility. Activity will become live when the backend is connected to verified data sources and persistence.</p></div><div className="sourceBanner"><Activity size={18}/><div><b>{activity.length?"Live agent activity":"No agent runs yet"}</b><span>{activity.length?`${activity.length} backend agent event${activity.length===1?"":"s"} recorded.`:"Run Career Coach or another agent to create a real backend activity record."}</span></div></div><div className="workflow"><div className="workflowLine"/>{agents.map((a,i)=><button className={expanded===i?"agent active":"agent"} key={a[0]} onClick={()=>setExpanded(i)}><div className="agentNo">{String(i+1).padStart(2,"0")}</div><div className="agentBadge">{i===0?<Search/>:i===1?<ShieldCheck/>:i===2?<TrendingUp/>:i===3?<Target/>:<Sparkles/>}</div><div className="grow"><b>{a[0]}</b><span>{a[1]}</span></div><span className="status"><Clock3 size={14}/> Awaiting data</span><ChevronDown className={expanded===i?"rot":""} size={16}/><div className={expanded===i?"agentDetail show":"agentDetail"}><b>Role in the workflow</b><p>{a[2]}. Results remain traceable to the records and sources used by the system.</p></div></button>)}</div></section>}

function PathModal({path,close,go}){return <div className="modalBack" onClick={close}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}><X/></button><span className="eyebrow">PATHWAY PROFILE</span><h2>{path.name}</h2><p>{path.desc}</p><div className="modalSection"><b>Typical role directions</b><div className="roleList">{path.roles.map(r=><span key={r}><Briefcase size={14}/>{r}</span>)}</div></div><div className="modalSection"><b>Core skills</b><div className="chips">{path.skills.map(s=><span key={s}>{s}</span>)}</div></div><div className="notice"><ShieldCheck size={16}/><span>Qualification and eligibility are contextual. The connected system will attach official sources before presenting them as verified facts.</span></div><button className="primary" onClick={()=>{close();go("AI Career Coach")}}>Build a roadmap <ArrowUpRight size={16}/></button></div></div>}
function OppModal({opp,close}){return <div className="modalBack" onClick={close}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}><X/></button><span className="eyebrow">{opp.type.toUpperCase()} OPPORTUNITY</span><h2>{opp.name}</h2><p className="modalOrg"><Building2 size={16}/>{opp.org}</p><div className="detailGrid"><span><MapPin size={15}/><b>Location</b>{opp.location}</span><span><CalendarDays size={15}/><b>Deadline</b>{opp.deadline}</span></div><div className="modalSection"><b>Pathway</b><p>{opp.path}</p></div><div className="modalSection"><b>Relevant skills</b><div className="chips">{opp.skills.map(s=><span key={s}>{s}</span>)}</div></div><div className="notice pendingNotice"><Clock3 size={16}/><span>This is a seed record. It is not presented as a verified live vacancy until an original source is checked.</span></div><button className="outlineBtn full"><ExternalLink size={15}/> Source link will appear after verification</button></div></div>}

createRoot(document.getElementById("root")).render(<App/>);