import React,{useEffect,useMemo,useState}from"react";
import{createRoot}from"react-dom/client";
import{LayoutDashboard,Map,Briefcase,MessageSquare,Activity,ChevronRight,Scale,Sparkles,Search,CheckCircle2,Clock3,ArrowUpRight,Menu,X,Target,BookOpen,ShieldCheck,Users,TrendingUp,ExternalLink,Filter,Send,UserRound,GraduationCap,Building2,CalendarDays,MapPin,Lightbulb,ChevronDown}from"lucide-react";
import"./styles.css";

const paths=[
{name:"Litigation & Advocacy",desc:"Courtroom and dispute work involving pleadings, evidence, hearings, appeals and client representation before Pakistani courts.",roles:["Advocate","Junior Associate","Legal Researcher","Law Clerk"],skills:["Legal Research","Pleading Drafting","Advocacy","Evidence Law"],qual:"LLB/BA-LLB; enrolment and bar requirements apply to practising advocates"},
{name:"Judiciary & Judicial Services",desc:"A court-focused route covering judicial research, legal reasoning, judgment writing and the institutional work of the Pakistani judiciary.",roles:["Law Clerk","Judicial Researcher","Civil Judge-cum-Magistrate","Judicial Officer"],skills:["Legal Research","Statutory Interpretation","Judgment Writing","Constitutional Law"],qual:"LLB/BA-LLB; judicial-service eligibility varies by jurisdiction"},
{name:"Corporate & Commercial Law",desc:"Advising companies and businesses on contracts, incorporation, governance, transactions, disputes and regulatory compliance.",roles:["Corporate Associate","In-house Counsel","Company Secretary","Transaction Lawyer"],skills:["Contract Drafting","Commercial Law","Negotiation","Legal Opinion Writing"],qual:"LLB/BA-LLB; corporate-law specialisation is useful"},
{name:"Government, Legislative & Regulatory Practice",desc:"Working with Parliament, ministries, regulators and public bodies on legislation, policy, regulation, legal opinions and administration.",roles:["Legislative Researcher","Legal Officer","Policy Associate","Regulatory Counsel"],skills:["Legal Research","Legislative Drafting","Policy Analysis","Constitutional Law"],qual:"LLB/BA-LLB; public-sector posts may impose additional criteria"},
{name:"Human Rights & Public Interest Law",desc:"Using law, research and advocacy to address constitutional rights, access to justice, discrimination and protection of vulnerable groups.",roles:["Human Rights Lawyer","Legal Aid Lawyer","Policy Advocate","Programme Officer"],skills:["Human Rights Law","Legal Research","Advocacy","Policy Analysis"],qual:"LLB/BA-LLB; research and advocacy experience is valuable"},
{name:"International Law & International Organisations",desc:"Applying public international law, human-rights law, humanitarian law and international institutional rules.",roles:["International Law Researcher","Legal Officer","Human Rights Officer","Policy Researcher"],skills:["International Law","Human Rights Law","Legal Research","Legal Writing"],qual:"LLB/BA-LLB; strong legal writing and English are important"},
{name:"Alternative Dispute Resolution & Arbitration",desc:"Resolving commercial and civil disputes through arbitration, mediation and related mechanisms.",roles:["Arbitration Associate","Legal Counsel","Mediator","Dispute Resolution Specialist"],skills:["Arbitration","Mediation","Negotiation","Contract Interpretation"],qual:"LLB/BA-LLB; arbitration training or experience is useful"},
{name:"Criminal Justice, Prosecution & Legal Investigation",desc:"Working across criminal litigation, prosecution, investigation, evidence and criminal-justice policy.",roles:["Criminal Lawyer","Prosecutor","Legal Investigator","Criminal Justice Researcher"],skills:["Criminal Law","Criminal Procedure","Evidence Law","Legal Research"],qual:"LLB/BA-LLB; public-sector posts have separate eligibility rules"},
{name:"Tax, Banking, Finance & Compliance",desc:"Advising financial institutions and businesses on taxation, banking regulation, securities, anti-money laundering, compliance and financial transactions.",roles:["Tax Lawyer","Banking Counsel","Compliance Officer","Financial Regulatory Lawyer"],skills:["Tax Law","Banking Law","Financial Regulation","Compliance"],qual:"LLB/BA-LLB; tax/finance specialisation is useful"},
{name:"Legal Academia, Research & Legal Technology",desc:"A research-oriented route combining teaching, legal scholarship, policy research, legal information systems and technology.",roles:["Research Assistant","Lecturer","Legal-Tech Analyst","Policy Researcher"],skills:["Legal Research","Legal Writing","Critical Thinking","Legal Technology"],qual:"LLB/BA-LLB; postgraduate study may be required for many academic roles"}]

const opps=[];

const API="/api";

async function api(path,options={}){const res=await fetch(API+path,{headers:{"Content-Type":"application/json",...(options.headers||{})},...options});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||"Request failed");return data}

const agents=[
["Research Agent","Collects candidate records from approved sources","Source discovery"],
["Verification Agent","Checks source, deadline, eligibility and freshness","Trust layer"],
["Career Intelligence Agent","Maps profiles to pathways and skill gaps","Career mapping"],
["Opportunity Matching Agent","Matches verified opportunities to student profiles","Personalisation"],
["Career Coach Agent","Creates grounded roadmaps and weekly actions","Action planning"]];

function App(){
 const[page,setPage]=useState("Dashboard"),[open,setOpen]=useState(false),[selectedPath,setSelectedPath]=useState(null),[selectedOpp,setSelectedOpp]=useState(null);
 const go=p=>{setPage(p);setOpen(false);window.scrollTo({top:0,behavior:"smooth"})};
 return <div className="app">
 <aside className={open?"side open":"side"}><div className="brand"><span className="mark"><Scale size={20}/></span><div><b>LegalPath</b><small>PAKISTAN</small></div></div>
 <div className="navLabel">WORKSPACE</div><nav>{[["Dashboard",LayoutDashboard],["Career Assessment",Target],["Career Map",Map],["Opportunities",Briefcase],["AI Career Coach",MessageSquare],["Agent Activity",Activity]].map(([n,I])=><button key={n} className={page===n?"nav active":"nav"} onClick={()=>go(n)}><I size={18}/>{n}</button>)}</nav>
 <div className="sideCard"><Sparkles size={16}/><b>Career intelligence</b><span>Grounded in verified data when connected.</span></div>
 <div className="sideFoot"><span>LEGALPATH PAKISTAN</span><small>AI career operating system for law students</small></div></aside>
 <main><header><div className="headerLeft"><button className="hamb" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><div><span className="eyebrow">LEGAL CAREER INTELLIGENCE</span><h1>{page}</h1></div></div><button className="profile" onClick={()=>go("AI Career Coach")}><UserRound size={17}/></button></header>
 {page==="Dashboard"&&<Dashboard go={go}/>} {page==="Career Assessment"&&<Assessment go={go}/>} {page==="Career Map"&&<CareerMap openPath={setSelectedPath}/>} {page==="Opportunities"&&<Opportunities openOpp={setSelectedOpp}/>} {page==="AI Career Coach"&&<Coach/>} {page==="Agent Activity"&&<Agents/>}
 </main>
 {selectedPath&&<PathModal path={selectedPath} close={()=>setSelectedPath(null)} go={go}/>}
 {selectedOpp&&<OppModal opp={selectedOpp} close={()=>setSelectedOpp(null)}/>}
 </div>
}

function Dashboard({go}){const[stats,setStats]=useState({pathways:paths.length,skills:"42+",agents:5,opps:0});useEffect(()=>{Promise.all([api("/career-pathways"),api("/skills"),api("/opportunities")]).then(([p,s,o])=>setStats({pathways:p.data?.length||paths.length,skills:(s.data?.length||0)+"",agents:5,opps:o.data?.length||0})).catch(()=>{});},[]);
 return <section className="content">
 <div className="hero"><div className="heroCopy"><span className="pill"><Sparkles size={14}/> AI-powered career intelligence</span><h2>Build your legal career<br/><em>with a clear path.</em></h2><p>LegalPath brings career pathways, skills, verified opportunities and AI-guided next steps into one workspace built for Pakistan's law students.</p><div className="actions"><button className="primary" onClick={()=>go("Career Map")}>Explore career paths <ArrowUpRight size={17}/></button><button className="secondary" onClick={()=>go("AI Career Coach")}>Build my roadmap</button></div></div><div className="heroVisual"><div className="orb"><Scale size={42}/></div><div className="orbStat"><b>10</b><span>career pathways</span></div><div className="orbit one"/><div className="orbit two"/></div></div>
 <div className="stats"><Stat icon={Map} value={String(stats.pathways).padStart(2,"0")} label="Career pathways"/><Stat icon={Target} value={stats.skills} label="Core skills"/><Stat icon={ShieldCheck} value={stats.opps} label="Opportunity records"/><Stat icon={Activity} value="05" label="AI agents"/></div>
 <div className="sectionHead"><div><span className="eyebrow">YOUR CAREER MAP</span><h3>Choose a direction</h3></div><button className="textBtn" onClick={()=>go("Career Map")}>View all <ChevronRight size={16}/></button></div>
 <div className="pathGrid">{paths.slice(0,5).map((p,i)=><button className="pathCard" key={p.name} onClick={()=>go("Career Map")}><span>0{i+1}</span><h4>{p.name}</h4><p>{p.desc}</p><div className="cardArrow"><ChevronRight/></div></button>)}</div>
 <div className="lower"><div className="panel"><div className="panelTitle"><div><span className="eyebrow">OPPORTUNITIES</span><h3>Opportunity pipeline</h3></div><button className="textBtn" onClick={()=>go("Opportunities")}>Browse all</button></div>{opps.slice(0,3).map(o=><button className="opp" key={o.name} onClick={()=>go("Opportunities")}><div className="oppIcon"><Briefcase size={17}/></div><div><b>{o.name}</b><small>{o.org} · {o.location}</small></div><span className="tag">{o.type}</span></button>)}</div>
 <div className="panel coachMini"><span className="pill"><Sparkles size={13}/> Career Coach</span><h3>Know your next move?</h3><p>Start with your target career, interests and current skills. The coach can turn them into an actionable plan.</p><button className="primary" onClick={()=>go("AI Career Coach")}>Open coach <ArrowUpRight size={16}/></button></div></div>
 </section>
}
function Stat({icon:I,value,label}){return <div className="stat"><div className="statIcon"><I size={17}/></div><div><b>{value}</b><span>{label}</span></div></div>}


function Assessment({go}){
 const[profile,setProfile]=useState({year:"",interests:"",skills:"",activities:"",environment:"",geography:"",research:"",advocacy:"",negotiation:"",publicSpeaking:""});
 const[result,setResult]=useState(null),[roadmap,setRoadmap]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const set=(k,v)=>setProfile(p=>({...p,[k]:v}));
 const submit=async()=>{setBusy(true);setError("");setRoadmap(null);setResult(null);try{const r=await api("/agents/assessment",{method:"POST",body:JSON.stringify({profile})});setResult(r);if(!r.pathways?.length)setError("Assessment completed, but no pathway results were returned.")}catch(e){setError(e.message)}finally{setBusy(false)}};
 const build=async(pathway)=>{setBusy(true);setError("");try{const r=await api("/agents/roadmap",{method:"POST",body:JSON.stringify({profile,pathway})});setRoadmap(r)}catch(e){setError(e.message)}finally{setBusy(false)}};
 const pipeline=[["01","Research Agent","Source discovery","Reads approved opportunity records when available"],["02","Verification Agent","Trust layer","Checks source, deadline and record validity"],["03","Career Intelligence Agent","Career mapping","Maps your evidence to career pathways and skill gaps"],["04","Opportunity Matching Agent","Personalisation","Matches your profile against verified opportunities"],["05","Career Coach Agent","Action planning","Turns a selected pathway into a practical 90-day experiment"]];
 return <section className="content"><div className="pageIntro"><span className="eyebrow">CAREER DISCOVERY ENGINE</span><h2>Discover your legal career direction.</h2><p>LegalPath uses a multi-agent workflow. Your result is an exploration hypothesis, not a fixed career label.</p></div>
 <div className="agentStrip"><div className="agentStripHead"><div><span className="eyebrow">LIVE AI WORKFLOW</span><h3>5 specialised agents</h3></div><span className="agentCount"><Activity size={14}/> {result?"Assessment run completed":"Ready to run"}</span></div><div className="agentPipeline">{pipeline.map(([n,name,role,desc],i)=><div className={result&&i<4?"pipelineAgent done":"pipelineAgent"} key={name}><span className="pipelineNo">{n}</span><div><b>{name}</b><small>{role}</small><span>{desc}</span></div>{result&&i<4?<CheckCircle2 size={16}/>:<Clock3 size={15}/>}</div>)}</div><div className="agentFoot"><ShieldCheck size={14}/> Opportunity records are only used after verification. No fake vacancies are generated.</div></div>
 <div className="assessmentGrid"><div className="assessmentForm">
 <div className="formSection"><span>01</span><div><b>Academic stage</b><small>Where are you in your law degree?</small></div></div>
 <label>Current year / semester</label><select value={profile.year} onChange={e=>set("year",e.target.value)}><option value="">Select</option><option>1st year</option><option>2nd year</option><option>3rd year</option><option>4th year</option><option>5th year</option><option>Graduate</option></select>
 <div className="formSection"><span>02</span><div><b>Your interests & evidence</b><small>Tell the system what you actually enjoy and have done.</small></div></div>
 <label>Interests</label><textarea value={profile.interests} onChange={e=>set("interests",e.target.value)} placeholder="e.g. international affairs, technology, human rights..."/>
 <label>Current skills</label><textarea value={profile.skills} onChange={e=>set("skills",e.target.value)} placeholder="e.g. research, writing, negotiation..."/>
 <label>Extracurricular activities / experience</label><textarea value={profile.activities} onChange={e=>set("activities",e.target.value)} placeholder="Moots, debates, internships, societies, research, volunteering..."/>
 <label>Preferred working environment</label><input value={profile.environment} onChange={e=>set("environment",e.target.value)} placeholder="Courtroom, corporate, research, public sector, flexible..."/>
 <label>Geographic preference</label><input value={profile.geography} onChange={e=>set("geography",e.target.value)} placeholder="City / province / Pakistan-wide"/>
 <div className="formSection"><span>03</span><div><b>Capability signals</b><small>Rate your current confidence from 1 to 5.</small></div></div>
 <div className="rangeGrid"><label>Research <input type="range" min="1" max="5" value={profile.research||3} onChange={e=>set("research",e.target.value)}/></label><label>Advocacy <input type="range" min="1" max="5" value={profile.advocacy||3} onChange={e=>set("advocacy",e.target.value)}/></label><label>Negotiation <input type="range" min="1" max="5" value={profile.negotiation||3} onChange={e=>set("negotiation",e.target.value)}/></label><label>Public speaking <input type="range" min="1" max="5" value={profile.publicSpeaking||3} onChange={e=>set("publicSpeaking",e.target.value)}/></label></div>
 <button className="primary full" disabled={busy} onClick={submit}><Target size={16}/>{busy?"Running 4 intelligence agents…":"Run career assessment"}</button>{error&&<div className="saved"><Clock3 size={16}/>{error}</div>}</div>
 <div className="assessmentResult"><div className="resultHeader"><div><span className="eyebrow">AI ASSESSMENT OUTPUT</span><h3>{result?"Your career hypotheses":"Your career exploration map"}</h3></div>{result&&<span className="liveBadge"><CheckCircle2 size={13}/> Live result</span>}</div><p>{result?result.note:"Complete the profile. Your evidence will be processed by the Career Intelligence Agent and ranked into five pathways."}</p>{result&&<div className="resultStatus"><CheckCircle2 size={16}/><div><b>Assessment complete</b><span>{result.pathways?.length||0} pathway hypotheses generated from your profile.</span></div></div>}
 {result?.pathways?.map((p,i)=><button className="hypothesis" key={p.pathway} onClick={()=>build(p.pathway)}><div><div className="hypothesisTop"><b>{i+1}. {p.pathway}</b><strong>{p.match_score} signal score</strong></div><span>{p.hypothesis}</span>{p.matched_skills?.length>0&&<small><b>Matched:</b> {p.matched_skills.join(", ")}</small>}{p.skill_gaps?.length>0&&<small><b>Skill gaps:</b> {p.skill_gaps.join(", ")}</small>}{p.evidence?.length>0&&<small><b>Evidence:</b> {p.evidence.map(e=>typeof e==="string"?e:(e.value||e.type||"signal")).join(", ")}</small>}</div><ChevronRight size={17}/></button>)}
 {!result&&<div className="resultEmpty"><Target size={24}/><b>Your results will appear here</b><span>After the assessment runs, you will see ranked pathways, evidence, skill gaps and a 90-day experiment.</span></div>}
 {roadmap&&<div className="roadmapBox"><div className="roadmapHead"><div><span className="eyebrow">CAREER COACH AGENT</span><h4>90-day experiment · {roadmap.pathway}</h4></div><span>{roadmap.stage}</span></div>{roadmap.skill_gaps?.length>0&&<p><b>Priority skill gaps:</b> {roadmap.skill_gaps.join(", ")}</p>}{roadmap.next_90_days.map((x,i)=><div className="roadStep" key={x}><span>0{i+1}</span>{x}</div>)}</div>}
 </div></div></section>
}

function CareerMap({openPath}){const[query,setQuery]=useState("");const filtered=paths.filter(p=>(p.name+p.desc).toLowerCase().includes(query.toLowerCase()));return <section className="content"><div className="pageIntro"><span className="eyebrow">CAREER PATHWAYS</span><h2>Explore the legal career landscape.</h2><p>Compare pathways by typical roles, core skills and qualification context. Final eligibility should always be checked against the relevant official source.</p></div><div className="mapTools"><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search pathways..."/></div><div className="toolNote"><BookOpen size={16}/> Explore a pathway to see its skill profile</div></div><div className="bigGrid">{filtered.map((p,i)=><article className="bigCard" key={p.name}><div className="cardTop"><span className="num">0{i+1}</span><span className="pathIcon"><Scale size={16}/></span></div><h3>{p.name}</h3><p>{p.desc}</p><div className="chips">{p.skills.slice(0,3).map(s=><span key={s}>{s}</span>)}</div><div className="line"/><div className="cardMeta"><span><Users size={14}/>{p.roles.length} role directions</span><span><GraduationCap size={14}/>{p.qual}</span></div><button className="outlineBtn" onClick={()=>openPath(p)}>Explore pathway <ChevronRight size={15}/></button></article>)}</div></section>}

function Opportunities({openOpp}){const[q,setQ]=useState(""),[type,setType]=useState("All"),[items,setItems]=useState(opps),[loading,setLoading]=useState(true);useEffect(()=>{api("/opportunities").then(r=>setItems((r.data||[]).map(o=>({name:o.title,org:o.organisation,type:o.type==="Employment"?"Government":o.type==="Research"?"Academia":o.type==="Internship"?"Research":"Corporate",path:o.pathway==="government"?"Government Legal Service":o.pathway==="corporate"?"Corporate / In-House Legal":"Legal Research & Academia",location:"Pakistan",deadline:o.deadline||"Not provided",skills:o.skills||[],status:o.verification_status==="verified"?"Verified":"Pending verification",source_url:o.source_url})))) .catch(()=>{}).finally(()=>setLoading(false));},[]);const filtered=useMemo(()=>items.filter(o=>(type==="All"||o.type===type)&&(o.name+" "+o.org+" "+o.path+" "+o.skills.join(" ")).toLowerCase().includes(q.toLowerCase())),[q,type]);return <section className="content"><div className="pageIntro"><span className="eyebrow">OPPORTUNITY INTELLIGENCE</span><h2>Find your next opportunity.</h2><p>Only records that pass the approved-source and verification pipeline become live recommendations. The initial dataset is intentionally small.</p></div><div className="oppToolbar"><div className="search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search roles, organisations or skills..."/></div><div className="filters">{["All","Research","Government","Academia","Corporate"].map(t=><button className={type===t?"filter active":"filter"} key={t} onClick={()=>setType(t)}><Filter size={13}/>{t}</button>)}</div></div><div className="table">{loading&&<div className="sourceBanner"><Clock3 size={18}/><div><b>Loading live backend records…</b><span>Fetching opportunity data from the LegalPath API.</span></div></div>}{filtered.map(o=><button className="opp row" key={o.name} onClick={()=>openOpp(o)}><div className="oppIcon"><Briefcase size={17}/></div><div className="grow"><b>{o.name}</b><small>{o.org} · {o.location}</small><div className="rowPath">{o.path}</div></div><span className="tag">{o.type}</span><span className="verified pending"><Clock3 size={14}/>{o.status}</span><ArrowUpRight size={17}/></button>)}</div>{!loading&&filtered.length===0&&<div className="emptyState"><ShieldCheck size={22}/><b>No verified opportunities yet</b><span>Live opportunities will appear here after the Research and Verification agents process approved sources.</span></div>}<div className="sourceBanner"><ShieldCheck size={18}/><div><b>Source-first design</b><span>Every live opportunity will carry an original source URL, verification status and date checked. No vacancy is treated as verified just because an AI model generated it.</span></div></div></section>}

function Coach(){const[goal,setGoal]=useState(""),[submitted,setSubmitted]=useState(false),[interest,setInterest]=useState(""),[answer,setAnswer]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");const submit=async()=>{setBusy(true);setError("");setAnswer("");try{const r=await api("/agents/coach",{method:"POST",body:JSON.stringify({profile:{interests:interest,target:goal},question:goal||"Create a practical career roadmap.",context:{career_pathways:paths}})});setAnswer(r.answer||"No answer returned.");setSubmitted(true)}catch(e){setError(e.message)}finally{setBusy(false)}};const prompts=["I am a law student and want a government legal career.","Help me choose between advocacy and corporate law.","What skills should I build for legal research?"];return <section className="content"><div className="coachPage"><span className="pill"><Sparkles size={14}/> Grounded AI Career Coach</span><h2>Turn your profile into<br/><em>a practical roadmap.</em></h2><p>The coach will use verified pathway and opportunity data once the backend is connected. For now, this screen captures the profile inputs the production coach will use.</p><div className="coachGrid"><div className="coachForm"><label>What is your career goal?</label><textarea value={goal} onChange={e=>setGoal(e.target.value)} placeholder="e.g. I want to prepare for a government legal role..."/><label>What area interests you most?</label><select value={interest} onChange={e=>setInterest(e.target.value)}><option value="">Select an area</option>{paths.map(p=><option key={p.name}>{p.name}</option>)}</select><button className="primary full" disabled={busy} onClick={submit}><Send size={16}/> {busy?"Generating…":"Generate roadmap"}</button>{error&&<div className="saved"><Clock3 size={16}/> {error}</div>}{answer&&<div className="saved"><CheckCircle2 size={16}/><span>{answer}</span></div>}{submitted&&!answer&&!error&&<div className="saved"><CheckCircle2 size={16}/> Profile input saved locally for this session.</div>}</div><div className="coachAside"><div className="coachHeader"><div className="coachAvatar"><Sparkles size={17}/></div><div><b>LegalPath Coach</b><span>Grounded AI workflow</span></div></div><p>Try a starting question:</p>{prompts.map(x=><button key={x} onClick={()=>setGoal(x)}>{x}<ChevronRight size={15}/></button>)}<div className="coachRule"><ShieldCheck size={15}/><span>No invented vacancies, deadlines or legal requirements.</span></div></div></div></div></section>}

function Agents(){
 const[expanded,setExpanded]=useState(0),[activity,setActivity]=useState([]);
 useEffect(()=>{const load=()=>api("/agents/activity").then(r=>setActivity(r.data||[])).catch(()=>{});load();const id=setInterval(load,5000);return()=>clearInterval(id)},[]);
 const latest=useMemo(()=>{const m=new Map();activity.forEach(x=>{if(!m.has(x.agent))m.set(x.agent,x)});return m},[activity]);
 return <section className="content"><div className="pageIntro"><span className="eyebrow">MULTI-AGENT SYSTEM</span><h2>AI workflow, with provenance.</h2><p>Each agent has a defined responsibility. The workflow is designed as Research → Verification → Career Intelligence → Matching → Career Coach. Activity is recorded only when an agent endpoint actually runs.</p></div>
 <div className="sourceBanner"><Activity size={18}/><div><b>{activity.length?"Live agent activity":"No agent runs yet"}</b><span>{activity.length?activity.length+" backend agent event"+(activity.length===1?"":"s")+" recorded.":"No backend agent events have been recorded in this session."}</span></div></div>
 <div className="workflow"><div className="workflowLine"/>{agents.map((a,i)=>{const run=latest.get(a[0]);const state=run?.status==="completed"?"Completed":run?.status==="failed"?"Failed":"Awaiting data";return <button className={expanded===i?"agent active":"agent"} key={a[0]} onClick={()=>setExpanded(i)}><div className="agentNo">{String(i+1).padStart(2,"0")}</div><div className="agentBadge">{i===0?<Search/>:i===1?<ShieldCheck/>:i===2?<TrendingUp/>:i===3?<Target/>:<Sparkles/>}</div><div className="grow"><b>{a[0]}</b><span>{a[1]}</span></div><span className={state==="Completed"?"status done":state==="Failed"?"status failed":"status"}>{state==="Completed"?<CheckCircle2 size={14}/>:<Clock3 size={14}/>} {state}</span><ChevronDown className={expanded===i?"rot":""} size={16}/><div className={expanded===i?"agentDetail show":"agentDetail"}><b>Role in the workflow</b><p>{a[2]}. {run?"Last run: "+new Date(run.timestamp).toLocaleString()+".":"This agent has not run yet."} Results remain traceable to the records and sources used by the system.</p></div></button>})}</div></section>
}
function PathModal({path,close,go}){return <div className="modalBack" onClick={close}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}><X/></button><span className="eyebrow">PATHWAY PROFILE</span><h2>{path.name}</h2><p>{path.desc}</p><div className="modalSection"><b>Typical role directions</b><div className="roleList">{path.roles.map(r=><span key={r}><Briefcase size={14}/>{r}</span>)}</div></div><div className="modalSection"><b>Core skills</b><div className="chips">{path.skills.map(s=><span key={s}>{s}</span>)}</div></div><div className="notice"><ShieldCheck size={16}/><span>Qualification and eligibility are contextual. The connected system will attach official sources before presenting them as verified facts.</span></div><button className="primary" onClick={()=>{close();go("AI Career Coach")}}>Build a roadmap <ArrowUpRight size={16}/></button></div></div>}
function OppModal({opp,close}){return <div className="modalBack" onClick={close}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}><X/></button><span className="eyebrow">{opp.type.toUpperCase()} OPPORTUNITY</span><h2>{opp.name}</h2><p className="modalOrg"><Building2 size={16}/>{opp.org}</p><div className="detailGrid"><span><MapPin size={15}/><b>Location</b>{opp.location}</span><span><CalendarDays size={15}/><b>Deadline</b>{opp.deadline}</span></div><div className="modalSection"><b>Pathway</b><p>{opp.path}</p></div><div className="modalSection"><b>Relevant skills</b><div className="chips">{opp.skills.map(s=><span key={s}>{s}</span>)}</div></div><div className="notice pendingNotice"><Clock3 size={16}/><span>This opportunity is only publishable after an original source has been checked and its provenance recorded.</span></div><button className="outlineBtn full"><ExternalLink size={15}/> Source link will appear after verification</button></div></div>}

createRoot(document.getElementById("root")).render(<App/>);